# Generated by Django 5.0.2 on 2024-03-01 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionhistory',
            options={'verbose_name_plural': 'Action Histories'},
        ),
    ]
