# Generated by Django 5.0.2 on 2024-04-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_actionhistory_nextaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionhistory',
            name='nextAction',
        ),
    ]
