# Generated by Django 5.0.2 on 2024-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_actionhistory_nextaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='promptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=100000)),
            ],
        ),
    ]
