# -*- coding: utf-8 -*-
"""ReAcT_Reflexion_Custom_Hospital.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_DY3cgFl9xPEG_xzJmIvrsARbZhiIJb
"""

!pip install openai

"""### Language Model"""

import os
from openai import AzureOpenAI

client = AzureOpenAI(
  azure_endpoint = "https://cnerg-gpt-france.openai.azure.com/",
  api_key="06cf45fb5c194e76805320b11bccf539",
  api_version="2023-05-15"
)

deployment_name='GPT-4-France'


def llm(prompt, stop=['\n']):
  response = client.chat.completions.create(
    model="GPT-4-France",
    messages=[
                {"role": "system", "content": "You are a helpful AI robot inside a hospital environment."},
                {"role": "user", "content": prompt} ],
    temperature=0,
    top_p=0.98,
    frequency_penalty=0,
    presence_penalty=0,
    stop=stop)
  return response.choices[0].message.content

import json
prompt_file = 'react_waste_2.json'
with open(prompt_file, 'r') as f:
    d = json.load(f)

prompt = 'Interact with the hospital environment to solve a task. Here are two examples.\n' + d[f'react_waste_1'] + d[f'react_waste_2'] + '\nHere is the task.\n'
# Evaluate variation-4
ob = "You are in the hallway. This is the main corridor in the ground floor from which we can go to other rooms. The rooms that we can go from here are : doctor chamber, general ward, common toilet, hallway nurse station. The room contains : wall poster, doctor #1. \nYour task is to : find all the waste products from the doctor chamber and put them on dustbin."
init_prompt = prompt + ob + '\n>'
prompt = ''

import sys

for i in range(1, 50):
  action = llm(init_prompt + prompt, stop=['\n']).strip()
  print(f"output= {action}")
  if action.startswith('think:'):
    observation = 'OK.'
  else:
    observation=    ####### GIVE THE CURRENT OBSERVATION #######

  print(f'Act {i}: {action}\nObs {i}: {observation}')
  sys.stdout.flush()
  prompt += f' {action}\n{observation}\n>'

print(init_prompt)

print(prompt)

file_path = '/content/mem.txt'

with open(file_path, 'w', encoding='utf-8') as file:
    file.write(prompt)

file1 = '/content/mem_1.txt'

with open(file1, 'r', encoding='utf-8') as file:
    content1 = file.read()

print(content1)

mem = init_prompt + content1
refl = "Feedback: In this environment, my plan was to find all the waste products in the doctor chamber and put them in the dustbin. However, after collecting only 2 waste items, and exploring only till the patient bed, I started to think that the task is completed. I should have looked for the other items which was the patient bed table in the doctor chamber which contained additional waste items. In the next trial, I will look for waste items in the patient bed table as well."
init_prompt = mem + '\n' + refl + '\nHere is the task.\n' + ob + '\n>'
prompt = ''

import sys

for i in range(1, 50):
  action = llm(init_prompt + prompt, stop=['\n']).strip()
  print(f"output= {action}")
  if action.startswith('think:'):
    observation = 'OK.'
  else:
    observation=input("obs= ")

  print(f'Act {i}: {action}\nObs {i}: {observation}')
  sys.stdout.flush()
  prompt += f' {action}\n{observation}\n>'

